#!/home/ubuntu/scripts/caffe_python.sh
import caffe
import numpy as np
import sys


def convert_proto_mean(proto_mean_file, numpy_output_file):
    """
    Convert a mean file generated by the `make_mean.sh` script into a numpy
    array which can be used in initializing training.

    This was originally found via:

    https://github.com/BVLC/caffe/blob/71e05876f644a08af4cb1c955d01c5a272539e96/python/caffe/io.py
    https://github.com/BVLC/caffe/blob/71e05876f644a08af4cb1c955d01c5a272539e96/examples/imagenet/make_imagenet_mean.sh

    Parameters
    ----------
    proto_mean_file : str
        Filename of the protobuf which describes the mean.
    numpy_output_file : str
        Filename to store the output as.
    """
    blob = caffe.proto.caffe_pb2.BlobProto()
    with open(proto_mean_file, 'rb') as proto_mean:
        data = proto_mean.read()

        blob.ParseFromString(data)
        arr = np.array(caffe.io.blobproto_to_array(blob))
        out = arr[0]

        np.save(numpy_output_file, out)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print """
        Convert a proto mean file to a numpy array to be used with Caffe.
        Usage: python convert_protomean.py proto.mean out.npy
        """
        sys.exit()

    convert_proto_mean(sys.argv[1], sys.argv[2])
